# Generated by Django 5.1 on 2025-03-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVENT_BOOKING', '0002_alter_decorationtransaction_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decorationtransaction',
            old_name='cart',
            new_name='user',
        ),
    ]
